export const GENESIS_CATALOG = [
  {
    id: 'desk-dragon-flexi',
    rank: 1,
    title: 'Dragon articulado de escritorio',
    category: 'Decoracion',
    likes: 18420,
    downloads: 62300,
    cover: 'dragon',
    slides: ['dragon', 'dragon-detail', 'dragon-scale'],
    description:
      'Pieza articulada para mostrar posibilidades de impresion flexible, texturas finas y acabado multicolor.',
  },
  {
    id: 'modular-tool-grid',
    rank: 2,
    title: 'Organizador modular de herramientas',
    category: 'Organizacion',
    likes: 16210,
    downloads: 54880,
    cover: 'grid',
    slides: ['grid', 'grid-wall', 'grid-box'],
    description:
      'Sistema de pared con modulos intercambiables para taller, escritorio o espacio maker.',
  },
  {
    id: 'planter-lowpoly',
    rank: 3,
    title: 'Maceta low-poly autorriego',
    category: 'Hogar',
    likes: 14870,
    downloads: 48110,
    cover: 'planter',
    slides: ['planter', 'planter-water', 'planter-side'],
    description:
      'Maceta decorativa con deposito oculto, ideal para mostrar geometria limpia y objetos utiles.',
  },
  {
    id: 'controller-stand',
    rank: 4,
    title: 'Soporte gamer para joystick',
    category: 'Gaming',
    likes: 13990,
    downloads: 45270,
    cover: 'controller',
    slides: ['controller', 'controller-back', 'controller-dual'],
    description:
      'Base estable para controles y auriculares, pensada para setups gamer y regalos personalizados.',
  },
  {
    id: 'phone-dock-magsafe',
    rank: 5,
    title: 'Dock de telefono con carga',
    category: 'Tech',
    likes: 12760,
    downloads: 43020,
    cover: 'dock',
    slides: ['dock', 'dock-cable', 'dock-desk'],
    description:
      'Dock compacto para escritorio con canal de cable integrado y angulo comodo para videollamadas.',
  },
  {
    id: 'drawer-divider-system',
    rank: 6,
    title: 'Separadores ajustables para cajon',
    category: 'Organizacion',
    likes: 11980,
    downloads: 39200,
    cover: 'drawer',
    slides: ['drawer', 'drawer-parts', 'drawer-layout'],
    description:
      'Kit parametrico para ordenar cajones de cocina, oficina o herramientas con piezas faciles de adaptar.',
  },
  {
    id: 'mini-architecture-house',
    rank: 7,
    title: 'Casa miniatura arquitectonica',
    category: 'Maquetas',
    likes: 11340,
    downloads: 37640,
    cover: 'house',
    slides: ['house', 'house-roof', 'house-window'],
    description:
      'Modelo de exhibicion para comunicar detalles, escalas y acabados en piezas de presentacion.',
  },
  {
    id: 'pokemon-style-display',
    rank: 8,
    title: 'Base de exhibicion coleccionable',
    category: 'Coleccionables',
    likes: 10880,
    downloads: 35920,
    cover: 'display',
    slides: ['display', 'display-card', 'display-light'],
    description:
      'Soporte para figuras o cartas, con espacio para placa de nombre y variantes de color.',
  },
  {
    id: 'cable-clip-pack',
    rank: 9,
    title: 'Pack de clips para cables',
    category: 'Utilitarios',
    likes: 9720,
    downloads: 33800,
    cover: 'clips',
    slides: ['clips', 'clips-desk', 'clips-set'],
    description:
      'Set simple y muy solicitado para ordenar cables en escritorios, mesas de noche y estaciones de carga.',
  },
  {
    id: 'lamp-geometric-shade',
    rank: 10,
    title: 'Pantalla geometrica para lampara',
    category: 'Iluminacion',
    likes: 9350,
    downloads: 30150,
    cover: 'lamp',
    slides: ['lamp', 'lamp-lit', 'lamp-top'],
    description:
      'Pantalla liviana con patron geometrico que permite jugar con sombras y filamentos translucidos.',
  },
  {
    id: 'board-game-insert',
    rank: 11,
    title: 'Inserto para juego de mesa',
    category: 'Gaming',
    likes: 8910,
    downloads: 28900,
    cover: 'insert',
    slides: ['insert', 'insert-tokens', 'insert-box'],
    description:
      'Organizador interno para cartas, fichas y dados; reduce setup y muestra precision dimensional.',
  },
  {
    id: 'kitchen-spice-rack',
    rank: 12,
    title: 'Rack compacto para especias',
    category: 'Hogar',
    likes: 8460,
    downloads: 27210,
    cover: 'spice',
    slides: ['spice', 'spice-wall', 'spice-labels'],
    description:
      'Estante modular para frascos chicos, con montaje simple y opcion de etiquetas personalizadas.',
  },
  {
    id: 'helmet-mini-stand',
    rank: 13,
    title: 'Soporte mini para casco o mascara',
    category: 'Cosplay',
    likes: 8140,
    downloads: 25400,
    cover: 'helmet',
    slides: ['helmet', 'helmet-profile', 'helmet-base'],
    description:
      'Base de exhibicion para cascos, mascaras o accesorios impresos, con buena presencia en vidriera.',
  },
  {
    id: 'fidget-gear-ring',
    rank: 14,
    title: 'Anillo fidget de engranajes',
    category: 'Juguetes',
    likes: 7920,
    downloads: 24180,
    cover: 'gear',
    slides: ['gear', 'gear-open', 'gear-hand'],
    description:
      'Pieza mecanica pequena que muestra tolerancias, movimiento suave y ensamblaje sin tornillos.',
  },
  {
    id: 'camera-cold-shoe-mount',
    rank: 15,
    title: 'Soporte cold shoe para camara',
    category: 'Tech',
    likes: 7510,
    downloads: 22870,
    cover: 'camera',
    slides: ['camera', 'camera-rig', 'camera-side'],
    description:
      'Accesorio funcional para creadores de contenido, con encastre para luces o microfonos livianos.',
  },
  {
    id: 'pet-bowl-riser',
    rank: 16,
    title: 'Elevador para comedero',
    category: 'Hogar',
    likes: 7240,
    downloads: 21340,
    cover: 'bowl',
    slides: ['bowl', 'bowl-feet', 'bowl-top'],
    description:
      'Base practica para comederos chicos, facil de limpiar y adaptable a medidas del cliente.',
  },
  {
    id: 'nameplate-custom',
    rank: 17,
    title: 'Placa personalizada para escritorio',
    category: 'Personalizados',
    likes: 6880,
    downloads: 20120,
    cover: 'nameplate',
    slides: ['nameplate', 'nameplate-side', 'nameplate-color'],
    description:
      'Producto de entrada para encargos personalizados: nombres, marcas, colores y soportes simples.',
  },
  {
    id: 'bike-light-bracket',
    rank: 18,
    title: 'Soporte de luz para bicicleta',
    category: 'Outdoor',
    likes: 6530,
    downloads: 19420,
    cover: 'bike',
    slides: ['bike', 'bike-clamp', 'bike-bar'],
    description:
      'Bracket resistente para accesorios livianos, util para explicar materiales y orientacion de capa.',
  },
  {
    id: 'earbud-case-holder',
    rank: 19,
    title: 'Holder para estuche de auriculares',
    category: 'Tech',
    likes: 6210,
    downloads: 18190,
    cover: 'earbuds',
    slides: ['earbuds', 'earbuds-clip', 'earbuds-desk'],
    description:
      'Portaestuche con clip y textura antideslizante, ideal para compras chicas y regalos.',
  },
  {
    id: 'holiday-cookie-cutter',
    rank: 20,
    title: 'Cortante tematico para reposteria',
    category: 'Hogar',
    likes: 5980,
    downloads: 17620,
    cover: 'cutter',
    slides: ['cutter', 'cutter-set', 'cutter-detail'],
    description:
      'Cortante personalizable por temporada, evento o marca; buen ejemplo de producto simple de alta demanda.',
  },
];
